### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by sathyajackson** [trackit/aws-cost-report#36]
I was looking for such kind of tool for a long time to do capacity management but i am not sure on how to use it and the what bucket information is needed or why API is needed.

Can you please add additional information to read me as to how to use to what are the buckets which the tools are requesting for.

**Comment by thibautcornolti** [comment]
Hi @sathyajackson 

## Set up

You have two ways to set up our tool:

### Classic

With this method, you have to install [python3](https://www.python.org/downloads) and [jq](https://stedolan.github.io/jq/) on your machine.

Then, open a terminal and type
```
git clone git@github.com:trackit/aws-cost-report.git
cd aws-cost-report
sudo pip3 install -r requirements.txt
```

You are now ready to use our Cost report generator.


### Docker

With this method, you have to install [docker](https://docs.docker.com/install/#supported-platforms)

Then, open a terminal and type

```
docker pull msolution/aws-cost-report
```

You are now ready to use our Cost report generator.

## Run

You will need an AWS account configured in your machine ([here](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html)) and a billing bucket (follow the *Setting Up AWS Bills* part [here](https://trackit.io/installing-setting-trackit-up-step-by-step/#Setting_Up_AWS_Bills) - do not forget to type a *Report path prefix*, unlike wrote in this article).

Your reports are periodically updated by AWS, please wait for reports in your bucket if you want billing information in your generated sheet.


Then choose how you want to run our tool, as you have chosen above.
For both methods, by default *profile_name* is `default`.

### Classic

```
./run.py --billing profile_name billing-bucket-name prefix --ec2 profile_name --xlsx-name filename
```

### Docker

```
docker run -v ~/.aws:/root/.aws:ro -v `pwd`/out:/root/aws-cost-report/out msolution/aws-cost-report --billing profile_name billing-bucket-name prefix --ec2 profile_name -xlsx-name filename
```

Voilà! Your report is generated at `./out/filename.xlsx`!

**If you have any question, please ask me!**

**Comment by sathyajackson** [comment]
Thanks will try, how about the UI ?, can we use the UI as well to get some fancy graph for the bills ?

**Comment by thibautcornolti** [comment]
Our UI is available in [this repository](https://github.com/trackit/trackit).
If you want to use easily TrackIt, I highly recommand using our self-hosted solution available at [TrackIt.IO](https://trackit.io).

**Comment by sathyajackson** [comment]
I got the dockers up and running and got the UI, but the UI is not allowing me to log in. I tried to register as well but still, i am not able to register.

**Comment by thibautcornolti** [comment]
Are you talking about [TrackIt](https://github.com/trackit/trackit)? If so, please open an issue [here](https://github.com/trackit/trackit/issues), so that our team will be able to help you. Please add logs into your issue.

Thanks.

**Comment by sathyajackson** [comment]
oh ok sure, thanks.

**Comment by sathyajackson** [comment]
Hello,

Sorry for very late responds, I have hooked up some other project. Alright, here we go, I used the classic version of the run.py and I end up with below error 

---------------------------
[ error ]
Traceback (most recent call last):
  File "src/make_xlsx.py", line 630, in <module>
    main(name)
  File "src/make_xlsx.py", line 612, in main
    gen_weekly_variations(workbook, header_format, val_format)
  File "src/make_xlsx.py", line 201, in gen_weekly_variations
    with open(IN_ABSOLUTE_COST_PER_MONTH) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'out/absolute.csv'
----------------------------------------------

Any suggestions would be of great help.
