### ISSUE TITLE
Sample data or screenshot

### ISSUE THREAD

**Issue by wtip** [trackit/aws-cost-report#9]
Can you provide a screenshot or csv file of the data output of this script?

**Comment by thibautcornolti** [comment]
Hi!
I'm glad to tell you we updated the README and added an example file.
Thanks.

**Comment by wtip** [comment]
that looks great. thanks!

**Comment by wtip** [comment]
![image](https://user-images.githubusercontent.com/3502082/38687111-e4db4728-3e43-11e8-8fd7-ee002ff5da39.png)
I tried to open the report-example.xlsx file and got this message.

**Comment by thibautcornolti** [comment]
Thanks for reporting this bug. We've found the problem, I'll keep you informed of its resolution.

EDIT: This issue is fixed.
